class Failure implements Exception {
  final String message;

  Failure([this.message = 'Ocurri√≥ un error inesperado']);
}
